---
- hosts: all
  become: true
  pre_tasks:

  - name: Install Fedora updates
    ansible.builtin.package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Install Ubuntu updates
    ansible.builtin.apt:
      upgrade: dist
      pdate_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: Install Apache on Web Servers
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  - name: Install MariaDB package
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"
